# Generated by Django 2.0.3 on 2018-03-27 19:09

from django.db import migrations, models
import challenge.application.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=56)),
                ('client_id', models.CharField(default=challenge.application.helpers.generate_application_client_id, max_length=32)),
                ('client_secret', models.CharField(default=challenge.application.helpers.generate_application_client_secret, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('client_id', 'client_secret')},
        ),
    ]
