# Generated by Django 2.2 on 2019-10-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('email', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
